<a href="https://colab.research.google.com/github/natthanich/BasicProg_DataViz65/blob/main/EXAMPLE_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HW 3
1. สร้าง array ที่เป็นต้น Christmas
2. Slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [ ]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[0,5] = 444
HW3[1,5] = 111
HW3[2,4:7] = 111
HW3[3,3:8] = 111
HW3[4,2:9] = 111
HW3[5,3:8] = 111
HW3[6,3:8] = 111
HW3[7,2:9] = 111
HW3[8,4:7] = 888
HW3[9,4:7] = 888
HW3[0,1] = 99
HW3[1,1] = 99
HW3[2,1] = 99
HW3[1,0] = 99
HW3[1,2] = 99

In [ ]:
HW3

array([[  0.,  99.,   0.,   0.,   0., 444.,   0.,   0.,   0.,   0.],
       [ 99.,  99.,  99.,   0.,   0., 111.,   0.,   0.,   0.,   0.],
       [  0.,  99.,   0.,   0., 111., 111., 111.,   0.,   0.,   0.],
       [  0.,   0.,   0., 111., 111., 111., 111., 111.,   0.,   0.],
       [  0.,   0., 111., 111., 111., 111., 111., 111., 111.,   0.],
       [  0.,   0.,   0., 111., 111., 111., 111., 111.,   0.,   0.],
       [  0.,   0.,   0., 111., 111., 111., 111., 111.,   0.,   0.],
       [  0.,   0., 111., 111., 111., 111., 111., 111., 111.,   0.],
       [  0.,   0.,   0.,   0., 888., 888., 888.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 888., 888., 888.,   0.,   0.,   0.]])

In [ ]:
# สร้าง array ที่เป็นต้น Christmas

In [ ]:
#Slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])